#!/bin/bash

# Define variables
URL="http://api-rrd.madavi.de:3000/grafana/d/GUaL5aZMz/pm-sensors?orgId=1&theme=dark&var-chipID=esp8266-12122974&var-type=DHT22&var-query0=sensors&refresh=1d&kiosk=tv&viewPanel=12"
OUTPUT_FILE="last24hours.png"

# Check if Node.js is installed
if ! command -v node &> /dev/null
then
    echo "Node.js is not installed. Please install Node.js and try again."
    exit 1
fi

# Check if npm is installed
if ! command -v npm &> /dev/null
then
    echo "npm is not installed. Please install npm and try again."
    exit 1
fi

# Check if git is installed
if ! command -v git &> /dev/null
then
    echo "git is not installed. Please install git and try again."
    exit 1
fi

# Check if capture-website-cli is installed
if ! command -v capture-website &> /dev/null
then
    echo "capture-website-cli is not installed. Please install capture-website-cli and try again."
    exit 1
fi

# Run capture-website command to capture website screenshot
if ! capture-website --
